# Generated by Django 3.2.7 on 2022-01-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRegistration',
            fields=[
                ('strategyid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('strategyname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('scripname', models.CharField(max_length=100)),
                ('entrycondition', models.CharField(max_length=100)),
                ('stoploss', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('exitcondition', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('createDate', models.CharField(max_length=50)),
                ('username', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Strategify.userregistration')),
            ],
        ),
    ]
