# Generated by Django 3.2.7 on 2022-03-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('deployid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scripname', models.CharField(max_length=100)),
                ('deploytime', models.CharField(max_length=100)),
                ('strategyid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Strategify.strategyregistration')),
            ],
        ),
    ]
