# Generated by Django 4.0.3 on 2022-03-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0002_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='algocycles',
            field=models.CharField(default=52, max_length=100),
            preserve_default=False,
        ),
    ]
