# Generated by Django 4.0.3 on 2022-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0004_deploy_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('accesstoken', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('consumerkey', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('appid', models.CharField(max_length=200)),
                ('accesscode', models.CharField(max_length=200)),
            ],
        ),
    ]
