# Generated by Django 4.0.3 on 2022-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0005_configure'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
