# Generated by Django 4.0.3 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0006_configure_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStrategy',
            fields=[
                ('strategyid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('strategyname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('scripname', models.CharField(max_length=100)),
                ('entrycondition', models.CharField(max_length=100)),
                ('stoploss', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('exitcondition', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
            ],
        ),
    ]
