# Generated by Django 4.0.3 on 2022-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0007_samplestrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScripList',
            fields=[
                ('symbol', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scrip', models.CharField(max_length=400)),
                ('instrumenttoken', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
    ]
