# Generated by Django 4.0.3 on 2022-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0010_rename_quantity_orders_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='condition',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
